name: PR-Agent-plus Workflow on Pull Requests

on:
  pull_request:
    branches:
      - main  # mainブランチに対するPull Requestでトリガー
    paths: 
      - '**.py'  # これでPythonファイルの変更のみをトリガーとして設定できます

jobs:
  code-review:
    runs-on: ubuntu-latest  # 実行環境
    env:  # 環境変数をここで設定
        PALM2_BASE_URL: https://generativelanguage.googleapis.com
        PALM2_MODEL_PATH: /v1beta2/models/text-bison-001:generateText

    steps:
      - name: Check out code
        uses: actions/checkout@v2  # リポジトリのコードをチェックアウト
        with:
            token: ${{ secrets.GH_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v2  # Python環境をセットアップ
        with:
          python-version: 3.8  # 使用するPythonのバージョン

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 必要なパッケージをインストール

      - name: Get changed files
        id: getfile
        run: |
          echo 'Files changed:'
          files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep .py) || echo "Error occurred with git diff or no files found."
          if [ -z "$files" ]; then
            echo "No Python files were changed."
            echo "::set-output name=files::"
            exit 0
          fi
          for file in ${files}; do
            echo $file
          done
          echo "::set-output name=files::$files"

      - name: Run Code Analyzer on changed files
        run: |
          IFS=' ' read -r -a files <<< "${{ steps.getfile.outputs.files }}"
          for file in "${files[@]}"; do
            python CodeAnalyzer/python_analyzer.py "$file" development_rules.jsonl
          done

      - name: Run Code Auto Fixer on changed files
        run: |
          IFS=' ' read -r -a files <<< "${{ steps.getfile.outputs.files }}"
          for file in "${files[@]}"; do
            python CodeAutoFixer/python_fixer.py "$file" development_rules.jsonl
          done

      - name: Generate Review Comment on changed files
        run: |
          IFS=' ' read -r -a files <<< "${{ steps.getfile.outputs.files }}"
          for file in "${files[@]}"; do
            python Review_Commenter/python_comment_generator.py "$file" 
          done
      - name: Post Review Comment on changed files
        run: |
          IFS=' ' read -r -a files <<< "${{ steps.getfile.outputs.files }}"
          for file in "${files[@]}"; do
            python post_comment.py "$file" ${{ secrets.GH_PAT }}
          done